### ISSUE TITLE
Numerous warnings and an error when compiling with gcc under Mac OS X

### ISSUE THREAD

**Issue by gpetty** [jfisteus/html2xhtml#13] opened 2015-08-17 04:46 UTC
Using ./configure, then make, I get numerous warnings that look like they might be unintentional usages of '=' (assignment) instead of '==' (logical equals). There is also a fatal error.  Diagnostic output shown below.   gcc --version yields the following

> Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
> Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
> Target: x86_64-apple-darwin12.5.0
> Thread model: posix

make  all-recursive
Making all in src
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT charset.o -MD -MP -MF .deps/charset.Tpo -c -o charset.o charset.c
charset.c:143:40: warning: incompatible pointer types passing 'int *' to parameter of type 'size_t *' (aka 'unsigned long *') [-Wincompatible-pointer-types]
    iconv (cd, NULL, NULL, &bufferpos, &avail);
                                       ^~~~~~
/usr/include/iconv.h:74:69: note: passing argument to parameter here
        char ** __restrict /*outbuf*/, size_t * __restrict /*outbytesleft*/);
                                                                           ^
charset.c:147:17: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
      if (wrote < 0) {
          ~~~~~ ^ ~
charset.c:194:37: warning: incompatible pointer types passing 'int *' to parameter of type 'size_t *' (aka 'unsigned long *') [-Wincompatible-pointer-types]
      nconv = iconv(cd, &bufferpos, &avail, &outbuf, &outbuf_max);
                                    ^~~~~~
/usr/include/iconv.h:73:68: note: passing argument to parameter here
        char ** __restrict /*inbuf*/,  size_t * __restrict /*inbytesleft*/,
                                                                          ^
charset.c:267:5: error: non-void function 'charset_write' should return a value [-Wreturn-type]
    return;
    ^
charset.c:274:48: warning: incompatible pointer types passing 'int *' to parameter of type 'size_t *' (aka 'unsigned long *') [-Wincompatible-pointer-types]
    nconv = iconv(cd, &bufpos, &n, &bufferpos, &avail);
                                               ^~~~~~
/usr/include/iconv.h:74:69: note: passing argument to parameter here
        char ** __restrict /*outbuf*/, size_t * __restrict /*outbytesleft*/);
                                                                           ^
charset.c:446:23: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
    } else if (buf[0] = 0x3c) {
               ~~~~~~~^~~~~~
charset.c:446:23: note: place parentheses around the assignment to silence this warning
    } else if (buf[0] = 0x3c) {
                      ^
               (            )
charset.c:446:23: note: use '==' to turn this assignment into an equality comparison
    } else if (buf[0] = 0x3c) {
                      ^
                      ==
charset.c:456:23: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
    } else if (buf[0] = 0x4c && buf[1] && buf[2] && buf[3]) {
               ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
charset.c:456:23: note: place parentheses around the assignment to silence this warning
    } else if (buf[0] = 0x4c && buf[1] && buf[2] && buf[3]) {
                      ^
               (                                          )
charset.c:456:23: note: use '==' to turn this assignment into an equality comparison
    } else if (buf[0] = 0x4c && buf[1] && buf[2] && buf[3]) {
                      ^
                      ==
charset.c:544:16: warning: implicit declaration of function 'tolower' is invalid in C99 [-Wimplicit-function-declaration]
    buf[len] = tolower(buffer[i]);
               ^
7 warnings and 1 error generated.
make[2]: *** [charset.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by jfisteus** [comment] 2015-08-19 16:02
Thanks for your report. I detail below the actions I've taken regarding this issue:

- The error (a return with no value) was fixed some time ago (see commit 78018250ece92a12d720fd77626996fec826087d). It was at the GitHub repository but not yet released, and this is way it still affected you.

- I've compiled in pedantic mode against the C99 standard and fixed most of the warnings I've got. Some remain because fixing them is not straightforward, but they don't seem relevant. I coudn't reproduce the one regarding int and sizet_t when calling iconv in my system.

- In addition to gcc, I compiled with clang, which according to the output you've posted is the actual compiler you are using, disguised as gcc.

- I've tested things in Linux (gcc and clang) and Windows (gcc from MinGW). I don't have access to a Mac OS X system.

Please, download the new version from http://www.it.uc3m.es/jaf/html2xhtml/downloads/html2xhtml-1.1.4.tar.gz, try it and let me know whether it compiles and which warnings remain in your system. If it compiles, please run also the tests:

```
cd tests
make test
```

**Comment by ricardo85x** [comment] 2015-09-17 18:24
Hi. I did have this problem on my mac too, and the 1.1.4 solved the problem.
Thanks

**Comment by jfisteus** [comment] 2015-09-18 08:17
Thanks for your feedback, ricardo85x. I'm closing the issue now. My plan to make the release of version 1.1.4 in a few days.

**Closed by jfisteus** 2015-09-18 08:17 UTC
